apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-demoapp
  name: nodejs-deployment
  namespace: cicdk8ns
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodejs-demoapp
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-demoapp
    spec:
      containers:
      - image: 911884746063.dkr.ecr.ap-south-1.amazonaws.com/nodejs-repo:latest
        name: nodejs-repo
        ports:
        - containerPort: 8080
        resources: 
          limits: 
            cpu: <based on requirement>
            memory: <based on requirement>
