apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-demoapp
  name: nodejs-svc
  namespace: cicdk8ns
spec:
  selector:
    app: nodejs-demoapp
  ports:
    - port: 3000
      targetPort: 8080
  type: LoadBalancer
