apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-demoapp
  namespace: cicdk8ns
spec:
  maxReplicas: 10
  minReplicas: 7
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: nodejs-demoapp
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  priorityClassName: system-node-critical  #Setting higher priority than daemonset pods
