apiVersion: v1
kind: Service
metadata: 
  creationTimestamp: null
  labels: 
    app: cicdk8
  name: cicdk8_svc
  spec: 
  selector: 
    app: nodejs-demoapp
  ports: 
    - port: 3000
      targetPort: 8080
  type: LoadBalancer
