apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-demoapp
  name: nodejs-deployment
  namespace: cicdk8ns
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodejs-demoapp
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-demoapp
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |-
          ACCOUNT=user
          REGION=my-region
          SECRET_NAME=${REGION}-ecr-registry
          TOKEN = 'aws ecr get-login --region ${REGION} --registry-ids ${ACCOUNT} | cut -d'
          kubectl create secret docker-registry $SECRET_NAME \
          --docker-server=https://${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com \
          --docker-username=AWS \
          --docker-password="${TOKEN}" \
          kubectl patch serviceaccount default -p '{"imagePullSecrets":[{"name":"'$SECRET_NAME'"}]}'
      - image: ${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/nodejs-test:latest
        name: nodejs-test
        ports:
        - containerPort: 8080
        resources: 
          limits: 
            cpu: <based on requirement>
            memory: <based on requirement
      priorityClassName: high-priority #Setting Higher priority than DeamonSet pods.   
